### ISSUE TITLE
differing timestamps & configurable timedelta

### ISSUE THREAD

**Issue by h82k** [DavideRossi/upback#3]
I've come across an issue where my files are considered having changed because of the timestamps.

The timestamps for my remote (WebDav on nextcloud) are like this

> 2019-01-25 00:15:06

while upback is comparing to local timestamps (Windows machine) like this

> 2019-01-25 00:15:06.000776

which is leading to conflicts, as both files seemingly have changed.

To be honest I don't understand why this happens. The json is created without specified milliseconds. How is the comparison to 10 microseconds possible? Otherwise I can only imagine that the local timestamp is supposed to be chopped of to only include the seconds.
A workaround could be a configurable timedelta although a solution working by default would be preferable.

I'm about to setup a new host with caddyserver and it's webdav plugin, so I can't test under the previous conditions. Maybe I can look if it is reproducable within the next week.

**Comment by DavideRossi** [comment]
Thanks for the report, I'll check this out. The current implementation considers timestamps not matching if there is a difference of more than 10 microseconds so this should not apply to your example, nevertheless I see that this can surely happen when a remote truncates timestamps to seconds.
My speculation is that rclone reports times in different formats (with/without milliseconds) depending on the remote that is used, or maybe webdav servers use different time accuracy. I guess the solution is to convert all times to the least accuracy and then make the comparison. It's not straightforward in the current implementation since where the comparison in performed the information about the remote are not available. Another issue here is that it's very hard to create a test case for that...

**Comment by DavideRossi** [comment]
I wrote some ugly workaround, let me know if it solves your problem. It should work better when rclone 1.46 is out.
